# Generated by Django 6.0 on 2026-08-18 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('requestId', models.CharField(max_length=100)),
                ('officerId', models.CharField(max_length=100)),
                ('assignedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenServiceRequest',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('citizenId', models.CharField(max_length=100)),
                ('citizenName', models.CharField(max_length=255)),
                ('citizenEmail', models.EmailField(max_length=254)),
                ('serviceId', models.CharField(max_length=100)),
                ('serviceName', models.CharField(max_length=255)),
                ('departmentId', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=255)),
                ('wardId', models.CharField(default='ward-112', max_length=100)),
                ('wardName', models.CharField(default='Ward 112 (Malleshwaram)', max_length=255)),
                ('submissionDate', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Department Received', 'Department Received'), ('Assigned', 'Assigned'), ('Under Verification', 'Under Verification'), ('Documents Required', 'Documents Required'), ('Under Processing', 'Under Processing'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Resolved', 'Resolved'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Submitted', max_length=100)),
                ('stage', models.CharField(max_length=255)),
                ('assignedOfficerId', models.CharField(blank=True, max_length=100, null=True)),
                ('assignedOfficerName', models.CharField(blank=True, max_length=255, null=True)),
                ('assignedOfficerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('evidenceName', models.CharField(blank=True, max_length=255, null=True)),
                ('evidenceType', models.CharField(blank=True, max_length=50, null=True)),
                ('evidenceSize', models.CharField(blank=True, max_length=50, null=True)),
                ('evidenceDataUrl', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('citizenEmail', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('requestId', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('eventType', models.CharField(max_length=100)),
                ('actorEmail', models.EmailField(max_length=254)),
                ('actorRole', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ipAddress', models.CharField(default='127.0.0.1', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Municipal Officer'), ('dept_admin', 'Department Administrator'), ('super_admin', 'Super Administrator')], default='citizen', max_length=50)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('departmentId', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('historyId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('previousStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('newStatus', models.CharField(max_length=100)),
                ('updatedBy', models.CharField(max_length=255)),
                ('updatedByRole', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.citizenservicerequest')),
            ],
            options={
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=255)),
                ('departmentId', models.CharField(max_length=100)),
                ('wardName', models.CharField(max_length=255)),
                ('authorizedServices', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to='api.user')),
            ],
        ),
    ]
